#!/bin/sh

set -e

if ! [ $# -eq 2 ]; then
  echo "Incorrect amount of parameters for runit finish script"
  exit 1
fi

SERVICE_EXIT_CODE=$1
SERVICE_EXIT_CODE_NORMAL=$2
SERVICE_BACKOFF_STATE_FILE=exponential-backoff
SERVICE_BACKOFF=3

echo "${PWD}: Determining exponential backoff..."

# Exponential backoff for this service
if [ -f $SERVICE_BACKOFF_STATE_FILE ]; then
  source $SERVICE_BACKOFF_STATE_FILE
fi


if ! [ -z $SERVICE_BACKOFF ]; then
  echo "${PWD}: Backoff for ${SERVICE_BACKOFF} seconds before resuming..."
  sleep $SERVICE_BACKOFF
  if [ $SERVICE_BACKOFF -lt 200 ]; then
    SERVICE_BACKOFF=$(($SERVICE_BACKOFF * 2))
    echo "SERVICE_BACKOFF=${SERVICE_BACKOFF}" > $SERVICE_BACKOFF_STATE_FILE
  fi
fi

exit $SERVICE_EXIT_CODE
