#!/bin/sh

PDNS_SETGID="${PDNS_SETGID:-pdns}"
PDNS_SETUID="${PDNS_SETUID:-pdns}"

# Define at least the random backend if none is specified
if ! (grep -qrE -e '^launch\+?=.+' /etc/pdns/ || [ -n "${PDNS_LAUNCH}" ]); then
  echo "No backends configured, falling back to 'random'."
  export PDNS_LAUNCH=random
  export PDNS_RANDOM_HOSTNAME="${PDNS_RANDOM_HOSTNAME:-random.example.com}"
fi

# Extract PDNS_ environment variables to their corresponding config variable
rm -f /etc/pdns/pdns.d/00environment.conf

for pdns_env_var in $(printenv | awk -F '=' '/^PDNS_/ { print $1 }' | sort); do
  pdnsvar=$(echo $pdns_env_var | sed -e 's/^PDNS_//' | tr '[:upper:]_' '[:lower:]-')
  if ! grep -qE -e "^${pdnsvar}$" /etc/pdns/allowed.settings; then
    continue
  fi
  pdnsval=$(eval "echo \${${pdns_env_var}}")
  printf "%s=%s\n" $pdnsvar $pdnsval >> /etc/pdns/pdns.d/00environment.conf
done

if [ ! -z $PDNS_DEBUG_ENV ]; then
  echo "=== PDNS_DEBUG_ENV enabled: environment:" >&2
  printenv | sort >&2
  if [ -f /etc/pdns/pdns.d/00environment.conf ]; then
    echo "=== PDNS_DEBUG_ENV enabled: /etc/pdns/pdns.d/00environment.conf" >&2
    cat /etc/pdns/pdns.d/00environment.conf >&2
  fi
fi

exec /usr/sbin/pdns_server \
  --daemon=no \
  --disable-syslog \
  --guardian=no \
  --setgid="${PDNS_SETGID}" \
  --setuid="${PDNS_SETUID}" \
  --write-pid=no $@
